-- ============================================================================
-- Valoraciones nutricionales (mensuales, por jugador)
-- ----------------------------------------------------------------------------
-- Una fila por jugador y periodo (mes). Permite acumular varios meses y
-- mostrarlos a la vez en la página "Valoraciones nutricionales".
--
-- Igual que el resto de tablas de la app: no se usa Supabase Auth (login
-- propio en app_users), así que las políticas RLS son abiertas (using true)
-- y el control de acceso (entrenador/preparador ven todo, jugador solo su
-- fila) se hace en el frontend.
--
-- EJECUTAR EN: Supabase Dashboard -> SQL Editor
-- ============================================================================

create table if not exists valoraciones_nutricionales (
  id bigint generated by default as identity primary key,
  periodo text not null,          -- 'YYYY-MM', p.ej. '2026-08'
  periodo_label text not null,    -- 'Agosto 2026'
  dorsal integer not null,
  jugador text not null,
  edad numeric,
  altura numeric,
  peso numeric,
  imc numeric,
  grasa_pct numeric,
  grasa_kg numeric,
  grasa_visceral numeric,
  musculo_pct numeric,
  musculo_kg numeric,
  met_basal numeric,
  brazo numeric,
  pecho numeric,
  abdomen numeric,
  gluteo numeric,
  b_gluteo numeric,
  pierna numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (periodo, dorsal)
);

alter table valoraciones_nutricionales enable row level security;

drop policy if exists "valoraciones_nutricionales_select" on valoraciones_nutricionales;
drop policy if exists "valoraciones_nutricionales_insert" on valoraciones_nutricionales;
drop policy if exists "valoraciones_nutricionales_update" on valoraciones_nutricionales;
drop policy if exists "valoraciones_nutricionales_delete" on valoraciones_nutricionales;

create policy "valoraciones_nutricionales_select" on valoraciones_nutricionales for select using (true);
create policy "valoraciones_nutricionales_insert" on valoraciones_nutricionales for insert with check (true);
create policy "valoraciones_nutricionales_update" on valoraciones_nutricionales for update using (true) with check (true);
create policy "valoraciones_nutricionales_delete" on valoraciones_nutricionales for delete using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'valoraciones_nutricionales'
  ) then
    alter publication supabase_realtime add table valoraciones_nutricionales;
  end if;
end $$;

-- ============================================================================
-- Datos iniciales: Agosto 2026 (archivo "Valoración nutricional Oyonesa
-- agosto 2026.xlsx")
-- ============================================================================
insert into valoraciones_nutricionales
  (periodo, periodo_label, dorsal, jugador, edad, altura, peso, imc, grasa_pct, grasa_kg, grasa_visceral, musculo_pct, musculo_kg, met_basal, brazo, pecho, abdomen, gluteo, b_gluteo, pierna)
values
  ('2026-08', 'Agosto 2026', 14, 'YASSINE', 19, 1.79, 78.1, 24.4, 23.1, 18.04, 6, 38.6, 30.15, 1766, 29.5, 87, 88, 108, 101, 62),
  ('2026-08', 'Agosto 2026', 20, 'MARC', 20, 1.74, 68.6, 22.7, 14.1, 9.67, 4, 44.3, 30.39, 1659, 32, 84, 78, 94, 92, 59.5),
  ('2026-08', 'Agosto 2026', 11, 'PEIO', 20, 1.76, 70.5, 22.8, 17.4, 12.27, 5, 42.1, 29.68, 1673, 30, 83, 81, 95, 92, 57),
  ('2026-08', 'Agosto 2026', 19, 'ISMA', 21, 1.77, 74.7, 23.8, 16.5, 12.33, 5, 42.5, 31.75, 1733, 30.5, 87, 80.5, 98, 93.5, 60),
  ('2026-08', 'Agosto 2026', 9, 'RUBÉN', 38, 1.8, 73.7, 22.7, 15.3, 11.28, 5, 40.8, 30.07, 1662, 29, 87, 82.5, 97, 95.5, 57.5),
  ('2026-08', 'Agosto 2026', 17, 'MARIO', 25, 1.76, 71.6, 23.1, 22.6, 16.18, 6, 37.9, 27.14, 1653, 29.5, 88.9, 88, 98, 93, 56),
  ('2026-08', 'Agosto 2026', 16, 'MANU', 22, 1.81, 79.8, 24.4, 11.2, 8.94, 5, 44.9, 35.83, 1798, 33.5, 92, 78.5, 96, 90, 58.5),
  ('2026-08', 'Agosto 2026', 1, 'MILLÁN', 21, 1.86, 90.9, 26.3, 21, 19.09, 7, 39.1, 35.54, 1932, 34, 94.5, 90, 103.5, 98, 62.5),
  ('2026-08', 'Agosto 2026', 6, 'MARCOS', 25, 1.84, 83.9, 24.8, 13.9, 11.66, 5, 42.8, 35.91, 1836, 32.5, 89, 87, 102.5, 99, 62),
  ('2026-08', 'Agosto 2026', 3, 'ÓSCAR', 32, 1.83, 82.4, 24.6, 14.8, 12.2, 7, 41.7, 34.36, 1796, 34.5, 88.5, 85, 100, 94, 62),
  ('2026-08', 'Agosto 2026', 4, 'PABLO', 28, 1.91, 92.2, 25.3, 18.5, 17.06, 7, 39.5, 36.42, 1921, 35.2, 96, 98, 103, 97, 61.3),
  ('2026-08', 'Agosto 2026', 2, 'ASIER', 24, 1.83, 77.3, 23.1, 14.3, 11.05, 4, 42.9, 33.16, 1751, 30.5, 87, 79, 99, 92, 57),
  ('2026-08', 'Agosto 2026', 5, 'MAESTRO', 34, 1.92, 95.5, 25.9, 25.6, 24.45, 8, 34.8, 33.23, 1934, 34.5, 92, 94.5, 110, 105, 66),
  ('2026-08', 'Agosto 2026', 15, 'IVÁN', 22, 1.92, 87.6, 23.8, 15.6, 13.67, 5, 41.6, 36.44, 1878, 34.5, 91, 85, 101, 98.5, 64),
  ('2026-08', 'Agosto 2026', 25, 'ADRIÁN', 26, 1.84, 71.3, 21.1, 17.9, 12.76, 3, 39.8, 28.38, 1635, 28.5, 83, 80, 97.5, 92.5, 55.3),
  ('2026-08', 'Agosto 2026', 7, 'JOSITO', 25, 1.75, 68.8, 22.5, 14.6, 10.04, 4, 43.3, 29.79, 1643, 29.5, 84, 76, 95.5, 91.5, 56),
  ('2026-08', 'Agosto 2026', 21, 'ALEJANDRO', 23, 1.95, 84.7, 22.3, 13.6, 11.52, 3, 42.4, 35.91, 1831, 32, 90.5, 86, 101.5, 95.5, 61),
  ('2026-08', 'Agosto 2026', 10, 'IÑAKI', 31, 1.78, 82.4, 26, 24, 19.78, 8, 37, 30.49, 1795, 29.5, 90.5, 90, 106.5, 102.5, 66),
  ('2026-08', 'Agosto 2026', 8, 'OLARTE', 26, 1.74, 77.1, 25.5, 20.2, 15.57, 7, 40.1, 30.92, 1753, 33, 88.5, 86, 100.5, 97, 62.5)
on conflict (periodo, dorsal) do update set
  periodo_label = excluded.periodo_label,
  jugador = excluded.jugador,
  edad = excluded.edad,
  altura = excluded.altura,
  peso = excluded.peso,
  imc = excluded.imc,
  grasa_pct = excluded.grasa_pct,
  grasa_kg = excluded.grasa_kg,
  grasa_visceral = excluded.grasa_visceral,
  musculo_pct = excluded.musculo_pct,
  musculo_kg = excluded.musculo_kg,
  met_basal = excluded.met_basal,
  brazo = excluded.brazo,
  pecho = excluded.pecho,
  abdomen = excluded.abdomen,
  gluteo = excluded.gluteo,
  b_gluteo = excluded.b_gluteo,
  pierna = excluded.pierna,
  updated_at = now();
